//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string AdminMenuCategories {
            get {
                return ResourceManager.GetString("AdminMenuCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string AdminMenuServices {
            get {
                return ResourceManager.GetString("AdminMenuServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times off.
        /// </summary>
        internal static string AdminMenuTimesOff {
            get {
                return ResourceManager.GetString("AdminMenuTimesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string AdminMenuTitle {
            get {
                return ResourceManager.GetString("AdminMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string AdminMenuUsers {
            get {
                return ResourceManager.GetString("AdminMenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20:00.
        /// </summary>
        internal static string CloseHour {
            get {
                return ResourceManager.GetString("CloseHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        internal static string HomeBook {
            get {
                return ResourceManager.GetString("HomeBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hariti Style Me.
        /// </summary>
        internal static string HomeHeading {
            get {
                return ResourceManager.GetString("HomeHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book your styling appointment in the most convenient for you time.
        /// </summary>
        internal static string HomeSubtitle {
            get {
                return ResourceManager.GetString("HomeSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        internal static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string LayoutAbout {
            get {
                return ResourceManager.GetString("LayoutAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string LayoutContact {
            get {
                return ResourceManager.GetString("LayoutContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hariti Style Me.
        /// </summary>
        internal static string LayoutLogo {
            get {
                return ResourceManager.GetString("LayoutLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string LoginPartialHello {
            get {
                return ResourceManager.GetString("LoginPartialHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginPartialLogin {
            get {
                return ResourceManager.GetString("LoginPartialLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LoginPartialLogout {
            get {
                return ResourceManager.GetString("LoginPartialLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string LoginPartialRegister {
            get {
                return ResourceManager.GetString("LoginPartialRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        internal static string ManageMenuAppointments {
            get {
                return ResourceManager.GetString("ManageMenuAppointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        internal static string ManageMenuSchedule {
            get {
                return ResourceManager.GetString("ManageMenuSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times off.
        /// </summary>
        internal static string ManageMenuTimesOff {
            get {
                return ResourceManager.GetString("ManageMenuTimesOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string ManageMenuTitle {
            get {
                return ResourceManager.GetString("ManageMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10:00.
        /// </summary>
        internal static string OpenHour {
            get {
                return ResourceManager.GetString("OpenHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string TimeSpanHoursSuffix {
            get {
                return ResourceManager.GetString("TimeSpanHoursSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string UserMenuBook {
            get {
                return ResourceManager.GetString("UserMenuBook", resourceCulture);
            }
        }
    }
}
